name: Run Weekly Stock Screener Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '45 11 * * 5'

jobs:
  run-python:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Set Timezone to IST
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          echo "Current Timezone: $(date)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Stock Screener Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          rm Report/latest_weekly
          report_file="Report/weekly_screeners_`date +'%Y-%m-%d_%H:%M'`.txt"
          # Download latest screeners
          python3 data/download_screener.py data/weekly_monthly_screener_config.json
          # Analyse the latest screeners and save result in a file
          python3 screener/getDataFromScreener.py --input-csvs-file data/downloaded_csvs.json --history-days 2 >> "$report_file"
          # Send Telegram Message
          python3 send_telegram.py $report_file
          cp $report_file Report/latest_weekly

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Report
          git commit -m "Auto-generated report at `date +'%Y-%m-%d_%H:%M'`" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
